package de.robnice.homeshoplist.wear.model

// Exact emojis from the phone app's ShoppingArea enum
val AREA_EMOJIS: Map<String, String> = mapOf(
    "produce"             to "🥦",
    "bakery"              to "🥖",
    "meat"                to "🥩",
    "fish_seafood"        to "🐟",
    "dairy_eggs"          to "🥛",
    "cheese_deli"         to "🧀",
    "groceries"           to "🛒",
    "milk"                to "🥛",
    "eggs"                to "🥚",
    "cold_cuts"           to "🥓",
    "refrigerated_cases"  to "🧊",
    "butcher_counter"     to "🔪",
    "area_1"              to "1️⃣",
    "area_2"              to "2️⃣",
    "area_3"              to "3️⃣",
    "area_4"              to "4️⃣",
    "area_5"              to "5️⃣",
    "area_6"              to "6️⃣",
    "area_7"              to "7️⃣",
    "area_8"              to "8️⃣",
    "impulse_buy"         to "🍬",
    "frozen"              to "❄️",
    "dry_goods"           to "🍾",
    "canned_jars"         to "🥫",
    "sauces_spices"       to "🧂",
    "breakfast"           to "🥣",
    "snacks_sweets"       to "🍫",
    "drinks"              to "🧃",
    "alcohol"             to "🍷",
    "coffee_tea"          to "☕",
    "household"           to "🏠",
    "cleaning"            to "🧽",
    "paper_goods"         to "🧻",
    "personal_care"       to "🧔",
    "baby"                to "🍼",
    "pet"                 to "🐾",
    "health"              to "💊",
    "non_food"            to "🛒",
    "other"               to "❔"
)
